In [9]:
from behavenet.fitting.hyperparam_utils import get_all_params
from behavenet.fitting.utils import build_data_generator
from behavenet.fitting.utils import create_tt_experiment
import pprint as pp
import numpy as np
import sys

In [10]:
import math

def count_nan(mat):
    c = 0
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            if math.isnan(mat[i][j]):
                c += 1
    return c

In [11]:
from scipy.io import loadmat
na = loadmat('../neural_dir/neural_activity2018-04-04_4_MD0ST5.mat')['neural_activity']
na.shape

(54602, 1452)

In [12]:
import os
os.path.expanduser('~/.behavenet')

'/home/yoni/.behavenet'

In [13]:
sys.argv = 'blank --data_config /home/yoni/.behavenet/decoding_data.json --model_config \
/home/yoni/.behavenet/decoding_ae_model.json --training_config /home/yoni/.behavenet/decoding_training.json --compute_config \
/home/yoni/.behavenet/decoding_compute.json'.split(' ')

sess_args = '--data_config /home/yoni/behavenet/decoding_data.json --model_config \
../.behavenet/decoding_ae_model.json --training_config ../.behavenet/decoding_training.json --compute_config \
../.behavenet/decoding_compute.json'.split(' ')

hparams = get_all_params(sess_args)
if not isinstance(hparams, dict):
    hparams = vars(hparams)

hparams, sess_ids, exp = create_tt_experiment(hparams)

/home/yoni/behavenet/results/dipoppa/full_trial/MD0ST5/4/neural-ae/09_latents/ff/None-single/grid_search/version_0/meta_tags.pkl
/home/yoni/behavenet/results/dipoppa/full_trial/MD0ST5/4/neural-ae/09_latents/ff/None-single/grid_search/version_1/meta_tags.pkl


In [19]:
hparams['subsample_idxs_name'] = 'inh_all'
hparams['subsample_idxs_group_1'] = 'cell_types'

print('Hyperparameters: ')
pp.pprint(hparams)
print('Session Ids: ', sess_ids, exp)

Hyperparameters: 
{'activation': 'relu',
 'ae_experiment_name': 'latent_search',
 'ae_model_type': 'conv',
 'ae_multisession': None,
 'ae_version': 'best',
 'animal': 'MD0ST5',
 'approx_batch_size': 200,
 'as_numpy': False,
 'batch_load': True,
 'compute_config': '/home/yoni/.behavenet/decoding_compute.json',
 'data_config': '/home/yoni/.behavenet/decoding_data.json',
 'data_dir': '/home/yoni/behavenet/data',
 'device': 'cpu',
 'early_stop_history': 10,
 'enable_early_stop': True,
 'experiment_name': 'grid_search',
 'export_predictions': True,
 'expt': 'full_trial',
 'expt_dir': '/home/yoni/behavenet/results/dipoppa/full_trial/MD0ST5/4/neural-ae/09_latents/ff/None-single/grid_search',
 'frame_rate': 30.0,
 'generate_trials': <bound method HyperOptArgumentParser.generate_trials of HyperOptArgumentParser(prog='blank', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)>,
 'gpus_viz': '0;1',
 'hpc_exp_number': None,
 'l2

In [20]:
data_generator = build_data_generator(hparams, sess_ids)

using data from following sessions:
/home/yoni/behavenet/results/dipoppa/full_trial/MD0ST5/4
constructing data generator...done
Generator contains 1 SingleSessionDatasetBatchedLoad objects:
dipoppa_full_trial_MD0ST5_4
    signals: ['neural', 'ae_latents']
    transforms: OrderedDict([('neural', Compose(SelectIndxs(idxs=idxs, sample_name=inh_all-single), ZScore(), )), ('ae_latents', None)])
    paths: OrderedDict([('neural', '/home/yoni/behavenet/data/dipoppa/full_trial/MD0ST5/4/data.hdf5'), ('ae_latents', '/home/yoni/behavenet/results/dipoppa/full_trial/MD0ST5/4/ae/conv/09_latents/latent_search/version_1/dipoppa_full_trial_MD0ST5_4_latents.pkl')])



In [21]:
import behavenet.data.utils as utils
print([key for key in utils.get_region_list(hparams)])
# for sess_id in sess_ids:
#     print(utils.get_transforms_paths('neural', hparams, sess_id))

['exc85_sample_0', 'exc85_sample_1', 'exc85_sample_10', 'exc85_sample_11', 'exc85_sample_12', 'exc85_sample_13', 'exc85_sample_14', 'exc85_sample_15', 'exc85_sample_16', 'exc85_sample_17', 'exc85_sample_18', 'exc85_sample_19', 'exc85_sample_2', 'exc85_sample_3', 'exc85_sample_4', 'exc85_sample_5', 'exc85_sample_6', 'exc85_sample_7', 'exc85_sample_8', 'exc85_sample_9', 'inh_all']


In [22]:
data, dataset = data_generator.next_batch('train')

print('AE Latents Size: ', data['ae_latents'].shape, '\n', 
      'Neural Size: ',     data['neural'].shape, '\n')

AE Latents Size:  torch.Size([1, 150, 9]) 
 Neural Size:  torch.Size([1, 150, 85]) 



In [9]:
sys.argv = 'blank --data_config ../.behavenet/dipoppa_test2_params.json --model_config \
../.behavenet/decoding_ae_model.json --training_config ../.behavenet/decoding_training.json --compute_config \
../.behavenet/decoding_compute.json'.split(' ')

args = '--data_config ../.behavenet/dipoppa_test2_params.json --model_config \
../.behavenet/decoding_ae_model.json --training_config ../.behavenet/decoding_training.json --compute_config \
../.behavenet/decoding_compute.json'.split(' ')

hparams = get_all_params(args)
if not isinstance(hparams, dict):
    hparams = vars(hparams)
    
hparams, sess_ids, exp = create_tt_experiment(hparams)
data_generator = build_data_generator(hparams, sess_ids)

standard = next(data_generator.dataset_iters[0]['train'])
    
print('AE Latents Size: ', data['ae_latents'].shape, '\n', 
      'Neural Size: ',     data['neural'].shape, '\n',
      'Num batches: ', data_generator.n_tot_batches['train'])

print(data)
print(data_generator.datasets[0].batch_idxs['train'])

FileNotFoundError: [Errno 2] No such file or directory: '../.behavenet/dipoppa_test2_params.json'

In [24]:
import torch

In [25]:
standard['neural'].shape, region_based['neural'].shape

NameError: name 'region_based' is not defined

In [68]:
standard['neural'], region_based['neural']

(tensor([[[ 0.3786, 17.4626,  0.0000,  ..., 20.2941,  0.0000, 11.5820],
          [ 1.7131, 16.5192,  0.0000,  ..., 36.0695,  0.0000, 20.5852],
          [ 3.0464, 15.5767,  0.0000,  ..., 51.8305,  0.0000, 29.5802],
          ...,
          [ 7.3460,  1.6241,  0.0000,  ..., 82.5977, 53.0828, 30.5647],
          [ 7.5909, 10.0097,  0.0000,  ..., 68.3756, 66.9368, 34.1036],
          [ 7.8358, 18.3991,  0.0000,  ..., 54.1470, 80.7972, 37.6441]]]),
 tensor([[[  9.2579,  35.9963,   0.0000,  ...,  48.0380,   8.9044, 100.7558],
          [  6.5598,  35.9261,   0.0000,  ...,  34.9450,   4.9271, 121.8596],
          [  3.8592,  35.8558,   0.0000,  ...,  21.8399,   0.9460, 142.9828],
          ...,
          [  2.1507,  34.3585,   0.0000,  ...,  32.8056,   0.0000,   0.0000],
          [  1.5019,  23.9932,   0.0000,  ...,  18.5968,   0.0000,   0.0000],
          [  0.8520,  13.6114,   0.0000,  ...,   4.3652,   0.0000,   0.0000]]]))

In [75]:
torch.eq(standard['neural'], region_based['neural'])

tensor([[[False, False,  True,  ..., False, False, False],
         [False, False,  True,  ..., False, False, False],
         [False, False,  True,  ..., False, False, False],
         ...,
         [False, False,  True,  ..., False, False, False],
         [False, False,  True,  ..., False, False, False],
         [False, False,  True,  ..., False, False, False]]])

In [30]:
import pandas as pd

df = pd.read_csv("results/dipoppa/test2/MD0ST5/4/neural-ae/09_latents/ff/sample_300-single/grid_search/version_0/metrics.csv")

In [31]:
df.head(10)

epoch  batch  dataset  trial     tr_loss      tr_r2  tr_fc  \
0      0     79       -1     -1  112.023133 -10.882368    0.0   
1      0     79       -1     -1         NaN        NaN    NaN   
2      1     79       -1     -1  104.267507 -10.098085    0.0   
3      1     79       -1     -1         NaN        NaN    NaN   
4      2     79       -1     -1   75.742481  -7.231776    0.0   
5      2     79       -1     -1         NaN        NaN    NaN   
6      3     79       -1     -1   65.056973  -6.297641    0.0   
7      3     79       -1     -1         NaN        NaN    NaN   
8      4     79       -1     -1   61.132606  -6.170390    0.0   
9      4     79       -1     -1         NaN        NaN    NaN   

                   created_at    val_loss     val_r2  val_fc  best_val_epoch  \
0  2020-02-29 22:56:27.865288         NaN        NaN     NaN             NaN   
1  2020-02-29 22:56:27.865949  110.322803 -20.186428     0.0             0.0   
2  2020-02-29 22:56:28.575496         NaN        NaN     NaN             NaN   
3  2020-02-29 22:56:28.576277   89.117474 -15.926996     0.0             1.0   
4  2020-02-29 22:56:29.271255         NaN        NaN     NaN             NaN   
5  2020-02-29 22:56:29.271898   73.285746 -12.590814     0.0             2.0   
6  2020-02-29 22:56:30.209814         NaN        NaN     NaN             NaN   
7  2020-02-29 22:56:30.210577   71.578273 -12.343989     0.0             3.0   
8  2020-02-29 22:56:31.741513         NaN        NaN     NaN             NaN   
9  2020-02-29 22:56:31.743654   71.265985 -12.397950     0.0             4.0   

   test_loss  test_r2  test_fc  
0        NaN      NaN      NaN  
1        NaN      NaN      NaN  
2        NaN      NaN      NaN  
3        NaN      NaN      NaN  
4        NaN      NaN      NaN  
5        NaN      NaN      NaN  
6        NaN      NaN      NaN  
7        NaN      NaN      NaN  
8        NaN      NaN      NaN  
9        NaN      NaN      NaN

In [33]:
df = pd.read_csv('results/dipoppa/test2/MD0ST5/4/neural-ae/09_latents/ff/sample_100-single/grid_search/version_0/meta_tags.csv')

In [34]:
df

key                                              value
0                  n_lags                                                  4
1                  l2_reg                                                0.1
2            n_hid_layers                                                  1
3             n_hid_units                                                 32
4     subsample_idxs_name                                         sample_100
..                    ...                                                ...
65          ae_model_path  /home/yoni/behavenet/results/dipoppa/test2/MD0...
66  ae_model_latents_file  /home/yoni/behavenet/results/dipoppa/test2/MD0...
67   model_build_rnd_seed  tensor([0, 0, 0,  ..., 0, 0, 0], dtype=torch.u...
68      training_rnd_seed  tensor([0, 0, 0,  ..., 0, 0, 0], dtype=torch.u...
69     training_completed                                               True

[70 rows x 2 columns]